### ISSUE TITLE
[ASK] [HELP] Using NCF how to get top 10 recommendations given a user_id and item_id?

### ISSUE THREAD

**Issue by karthikraja95** [microsoft/recommenders#1067]
### Description

I built a recommender system using NCF.  My question: is there a way to have a function takes in both user_id and item_id and gives recommendations based on the user_id history/transactions  and items similar to item_id?

Example: Let say user_id: 1234 purchases an item_id 2345. How to give top 10 item recommendations considering the user_id 1234 bought item_id 2345?

Any idea how to implement this using implicit NCF model?

**Comment by yueguoguo** [comment]
Not sure if I understand the example correctly... The NCF is not modeling the user-item interactions by using similarities. It is leveraging a generalized matrix factorization method to find user/item latent factors, together with the multi-layer perceptron neural network to find high-level user/item features, for recommendation. 

You can do pure item similarity recommendation by using SAR because it is a similarity based model. Or, you can use all of the user-item historical data, including user 1234, item 2345, and other users and items, to build a NCF model to recommend items to user 1234. 

Does it help?
