### ISSUE TITLE
[BUG] AttributeError: module 'papermill' has no attribute 'record'

### ISSUE THREAD

**Issue by ucasiggcas** [microsoft/recommenders#1112]
### Description
when I run the [script](https://github.com/microsoft/recommenders/blob/master/notebooks/00_quick_start/xdeepfm_criteo.ipynb),
up the error,
```
    pm.record("res_syn", res_syn)
AttributeError: module 'papermill' has no attribute 'record'

```
could you help me ?
thx

### In which platform does it happen?
```
>>> import papermill as pm
>>> pm.__version__
'2.1.1'
```
### How do we replicate the issue?
```
>>> import papermill as pm
>>> pm.record()
    pm.record()
AttributeError: module 'papermill' has no attribute 'record'
```
### Expected behavior (i.e. solution)
No error

**Comment by gramhagen** [comment]
we're using an older version of [papermill 0.19.1](https://github.com/microsoft/recommenders/blob/558733f366983d576953a407ab7180b1642dbc5b/scripts/generate_conda_file.py#L60). at [1.0.0](https://papermill.readthedocs.io/en/latest/changelog.html?highlight=record#id7) they removed record(), you can reinstall an older version with something like
```
pip install papermill==0.19.1
```
but if this is versioning is out of synch there may be other issues, the instructions in [SETUP.md](https://github.com/microsoft/recommenders/blob/master/SETUP.md) walk through how to set up the environment so that notebooks will run as expected.
