### ISSUE TITLE
[ASK] problems in test

### ISSUE THREAD

**Issue by Jazzssmine** [microsoft/recommenders#1340]
### Description
When adding test files in model.fit(), the evaluation results are the same between validate file and testing file. Is it possible that there is a problem in initing behaviors?

**Comment by gramhagen** [comment]
can you provide more detail on where this happens / which model is affected?

**Comment by YJack0000** [comment]
![Screen Shot 2021-06-02 at 12 31 44 AM](https://user-images.githubusercontent.com/49984479/120359140-e9eb5b80-c339-11eb-83cb-195cee2bc8ce.png)
I think he is talking about this result. I have the same problem.

**Comment by YJack0000** [comment]
I think #192 has similar problems. And after look into my prediction.txt file(generated by the code below). I think its because the model.run_eval() seemed considered valid_news_file and valid_behaviors_file as test_news_file and test_behaviors_file. So the prediction.txt is actually the result of model.run_eval(valid_news_file, valid_behaviors_file).
But I don't know why.
`
group_impr_indexes, group_labels, group_preds = model.run_fast_eval(test_news_file, test_behaviors_file)
with open(os.path.join(data_path+'/nrms', 'prediction.txt'), 'w') as f:
    for impr_index, preds in tqdm(zip(group_impr_indexes, group_preds)):
        impr_index += 1
        pred_rank = (np.argsort(np.argsort(preds)[::-1]) + 1).tolist()
        pred_rank = '[' + ','.join([str(i) for i in pred_rank]) + ']'
        f.write(' '.join([str(impr_index), pred_rank])+ '\n')
`

**Comment by miguelgfierro** [comment]
Closing since there hasn't been interaction for a while
