### ISSUE TITLE
[BUG] Latex in als_movielens_diversity_metrics.ipynb not rendering properly

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1479]
### Description

The formulas are not rendering in the notebook: https://github.com/microsoft/recommenders/blob/staging/examples/03_evaluate/als_movielens_diversity_metrics.ipynb

I can see the code with $$

### Other Comments
FYI @anargyri @YanZhangADS

**Comment by anargyri** [comment]
This is strange, because it shows well on Jupyter or VSCode.
It is more general in fact, also other notebooks have the same issue e.g. https://github.com/microsoft/recommenders/blob/staging/examples/02_model_collaborative_filtering/sar_deep_dive.ipynb
I recall the formulas used to render properly in the SAR notebook until recently.

**Comment by miguelgfierro** [comment]
Dup of https://github.com/microsoft/recommenders/issues/1567
