### ISSUE TITLE
[FEATURE] OOM in NCFDataset and in RBM affinity matrix

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1561]
### Description

We get an out of memory error when we process the data
![image](https://user-images.githubusercontent.com/3491412/139652312-2ccbec6a-8ae5-4445-b030-228144506fb4.png)
We think that the error comes from here
https://github.com/microsoft/recommenders/blob/main/recommenders/models/ncf/dataset.py
function def _init_train_data(self): (line 140)
![image](https://user-images.githubusercontent.com/3491412/139652382-1ef9893c-6b8d-4a91-9d2a-9ce41da58826.png)
In line 155 the function does save all the item pool for every customer,
With a sparse format we have 44M rows, and 0.88 GB, but with a full matrix this would become 18186 M rows and thus the OOM error.

There was a similar error when trying out the RBM notebook and the AffinityMatrix function.

**Comment by pradnyeshjoshi** [comment]
**Issue with RBM Notebook**

For `10m` and `20m` movielens datasets, `numpy_stratified_split` function gives the following error:
<img src="https://user-images.githubusercontent.com/10154413/143959374-40feb5c1-2727-4e13-bd5e-918e29c5d285.png" width="700" height="250">

This happens when `idx_test` is an empty list, because for some users, the corresponding row in `X` is all zeros. (See [line 288](https://github.com/microsoft/recommenders/blob/27709229cdc4aa7d39ab715789f093a2d21d2661/recommenders/datasets/python_splitters.py#L268).)

The reason for this is that the ratings in `10m` and `20m` datasets range from 0.5 to 5 in increments of 0.5. When they are converted to `int32` in the Load Data section of the notebook,

 `# Convert to 32-bit in order to reduce memory consumption`
`data.loc[:, 'rating'] = data['rating'].astype(np.int32)`

0.5 is rounded down to 0. For users that have only given a rating of 0.5, we get a row of all zeros. Removing this line resolves the error.

**Comment by miguelgfierro** [comment]
@pradnyeshjoshi this is good, however, the error you are getting is different to the OOM error that has been reported?

**Comment by pradnyeshjoshi** [comment]
> @pradnyeshjoshi this is good, however, the error you are getting is different to the OOM error that has been reported?

@miguelgfierro I did not come across any OOM issues while data preprocessing as mentioned in the issue with any of the movielens datasets (works for all 100k/1m/10m/20m). I did however come across an OOM issue while model fitting for 10m and 20m datasets, and I have created a [task](https://msazure.visualstudio.com/One/_sprints/taskboard/AGCI%20AI%20-%20Retail/One/28-Ni/2%20Wk%20Sprints/Sprint%2011?workitem=12774467) to look into that.

**Comment by miguelgfierro** [comment]
> With a sparse format we have 44M rows, and 0.88 GB, but with a full matrix this would become 18186 M rows and thus the OOM error.

@pradnyeshjoshi if you execute the line of code here with movielens 20M, do you see a similar growth in memory footprint? I'm afraid that we found another error, but we are not solving the original error that was reported
