### ISSUE TITLE
[BUG] Error when publishing to pypi with pymanopt

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1597]
### Description

When publishing to pypi the current code, I get an error:
```
$ twine upload lib/*
Uploading distributions to https://upload.pypi.org/legacy/
/anaconda/envs/py38_default/lib/python3.8/site-packages/twine/auth.py:66: UserWarning: Failed to create the collection: Prompt dismissed..
  warnings.warn(str(exc))
Enter your username: miguelgfierro
/anaconda/envs/py38_default/lib/python3.8/site-packages/twine/auth.py:75: UserWarning: Failed to create the collection: Prompt dismissed..
  warnings.warn(str(exc))
Enter your password:
Uploading recommenders-1.0.0-py3-none-manylinux1_x86_64.whl
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 334k/334k [00:01<00:00, 309kB/s]
Error during upload. Retry with the --verbose option for more details.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Invalid value for requires_dist. Error: Can't have direct dependency: 'pymanopt @ https://github.com/pymanopt/pymanopt/archive/fb36a272cdeecb21992cfd9271eb82baafeb316d.zip'

```
We need to find a good dependency for pymanopt that works with TF2 and the numpy version we have

**Comment by miguelgfierro** [comment]
FYI @bamdevm @pratikjawanpuria in case you can take a look

FYI @anargyri

**Comment by anargyri** [comment]
FYI this is a deliberate feature of PyPI for security reasons, see the discussion [here](https://github.com/pypa/pip/issues/6301).

**Comment by anargyri** [comment]
Summary of current state of incompatibilities with pymanopt:

1) Using pre-release 0.2.6rc1, the test `tests/unit/recommenders/models/test_geoimc.py::test_imcproblem` fails with
```
ValueError: Function 'cost' must be decorated with one of the decorators from 'pymanopt.function'
```

2) Using the latest release (0.2.5) raises the error
```
ImportError: cannot import name 'SymmetricPositiveDefinite' from 'pymanopt.manifolds'
(/anaconda/envs/pymanopt_025/lib/python3.7/site-packages/pymanopt/manifolds/__init__.py)
```

3) Earlier releases (<= 0.2.4) fail in other ways.

Also, we cannot use a direct URL that points to the pymanopt repository because PyPI does not allow this.

**Comment by anargyri** [comment]
Because of the above, I will exclude pymanopt from `setup.py`, but will provide instructions for users to install it manually if required.

**Comment by bamdevm** [comment]
Thanks, Andreas and Miguel, for bringing this to our attention.

Due to resources constraints, we have been very very slow. My sincere
apologies for that.

We will definitely try to reformulate the coding a bit at the earliest
possibility. In the meantime, may I request you take any step that you may
fit appropriate including the ones that Andreas suggested?

Regards,
Bamdev

**Comment by anargyri** [comment]
Thanks Bamdev,

No worries about the response! We will likely proceed as I described above, since we are very close to publishing the new release of recommenders. 
However, it may be easy for you to fix one of the errors when you find some time e.g. the cost function signature, if you are familiar with the changes in the pymanopt API.
Another thing you could do perhaps is to publish the intermediate commit that we have tested (`fb36a272cdeecb21992cfd9271eb82baafeb316d`) on PyPI as a release or pre-release. That would allows us to put pymanopt back in `setup.py`.

**Comment by anargyri** [comment]
> Because of the above, I will exclude pymanopt from `setup.py`, but will provide instructions how to install it manually if required.

See PR #1602
