### ISSUE TITLE
[BUG] Pytest marker warnings from the tests

### ISSUE THREAD

**Issue by simonzhaoms** [microsoft/recommenders#1843]
### Description

There are a long list of PytestUnknownMarkWarnings making it difficult to identify the real errors in the tests.
For example, see [the test outputs](https://github.com/microsoft/recommenders/actions/runs/3437629951/jobs/5732650237#step:3:1481) from the PR https://github.com/microsoft/recommenders/pull/1842

**Comment by miguelgfierro** [comment]
@simonzhaoms would you have time to work on this during the following days? The reason I'm asking is because it would also be nice to add the duration of the tests and maybe decouple the part where we build the library with the part we execute the tests, so it is easier to understand the logs. Right now we have everything in execute tests, see https://github.com/microsoft/recommenders/actions/runs/3485981939/jobs/5832009368

**Comment by simonzhaoms** [comment]
@miguelgfierro Sure, I can take a look today or tomorrow.
