### ISSUE TITLE
Script to automatize the installation of Recommenders repo on Databricks

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#237]
### *What* is affected by this bug?
Automatize the process of setting up the repo in databricks.

zip folder
```
cd Recommenders
zip -r Recommenders.zip .
```
use databricks cli to upload the zip
install conda on the cluster
install the conda dependencies

### *Where* on the platform does it happen?
*For example:*
 *Azure Databricks.*

### Expected behavior (i.e. solution)
./install_databricks

**Comment by loomlike** [comment]
@miguelgfierro I made and tested the script. Only issue of this approach is, it requires databricks CLI installation and onetime-setup of token. I'm working on updating SETUP.md as well. Will make PR once done.

### Expected behavior (i.e. solution)
* Simply run `./scripts/databricks_install.sh <YOUR_CLUSTER_ID>`

**Comment by miguelgfierro** [comment]
looks great!
