### ISSUE TITLE
python evaluation "KeyError: 'rating'" when a result DataFrame includes a col_rating column

### ISSUE THREAD

**Issue by loomlike** [Microsoft/Recommenders#377]
### *What* is affected by this bug?
Python evaluation module

### *How* do we replicate the issue?
If `col_rating != col_prediction` and the result dataframe has both `col_rating` and `col_prediction` columns, `_merge_rating_true_pred` module's merge operation will change `col_rating` name as `col_rating`"_x" and `col_rating`"_y" automatically, which causes "KeyError: 'rating'" error.

### Expected behavior (i.e. solution)
Since I explicitly pass the rating column name and prediction column name when I call the evaluation functions, I expect the functions to work with a result DataFrame that has `col_prediction` column and a ground-truth DataFrame that has `col_rating` column. Even if the result DataFrame has `col_rating` in addition to the `col_prediction`, the functions should ignore that and work as expected.

**Comment by yueguoguo** [comment]
@loomlike in designing the interface, the input dataframes should contain one of the two columns, either col_rating or col_prediction. The assumption is that the result DataFrame does not have both rating and prediction columns, otherwise it may not be necessary to have ground-truth and result DataFrames separated because the result DataFrame already contains both...

Probably some early-failing check is needed in the function to make sure inputs satisfy the requirements. What do you think?

**Comment by loomlike** [comment]
@yueguoguo Like the idea of early-failing. Probably check the input DataFrames and raise error at the beginning.

**Comment by yueguoguo** [comment]
Fixed in #383
