### ISSUE TITLE
python_evaluation.py ranking metrics raise assert error instead of returning 0.0 

### ISSUE THREAD

**Issue by loomlike** [Microsoft/Recommenders#410]
### *What* is affected by this bug?
python_evaluation.py ranking metrics raise assert error instead of 0.0 when there is no 'hit' items in the recommended list
(and...yes, I'm testing w/ a super poor model that produces 0.0 precision & recall in top-10 recommendation)

### In *which* platform does it happen?
* python

### *How* do we replicate the issue?
* Use a ground-truth dataframe and top_10_recommendation_result where the model performed so poor so that none of 10 items were in the ground-truth data 

### Expected behavior (i.e. solution)
instead of assertion error, returns 0.0 for ndcg, precision, recall, and map when hit_df is empty

**Comment by yueguoguo** [comment]
@loomlike to better understand the issue, regarding the use case, do you mean for **all of the users** there is no hit or for **some users** there is no hit. If it is the former, do you expect a 0.0 instead of an assertion error, is that correct? 

The initiative of this design is that asserting error is useful to imply that the recommendation system is not working at all (mostly this is because there is some issue with the code itself) rather than the recommendation system is performing poorly in ranking evaluations.

**Comment by miguelgfierro** [comment]
small detail, it is a good practice to throw an exception instead of using `assert`. The exception can be easily controlled, while the assert is more complicated

**Comment by yueguoguo** [comment]
@miguelgfierro that is good suggestion.

**Comment by loomlike** [comment]
@yueguoguo yes, all of the users and no hit. Let's say someone want to build 'I'm feeling lucky' recommender (k=1), then no hit can happen for the top-1 reco results.

**Comment by yueguoguo** [comment]
@loomlike I see. This is a good example.
