### ISSUE TITLE
[DISCUSSION] Should we allow deep learning algos in both CPU&GPU environment or only GPU env

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#436]
What should we do about this? Right now we designed the tests and some algos assuming that deep learning algos will always have a GPU env. 

Should we allow CPU&GPU environment as well, or only CPU?

**Comment by yueguoguo** [comment]
GPU only. My two cents: 

* DNN training on CPU is feasible but not preferred as known to all. We may want to recommend best practices to users about which platform to choose for running DNN with the highest efficiency. 
* Running DNN algorithms on CPU machine can be time consuming. Note our current DevOps pipeline has only one agent of VM (GPU incorporated), testing of multiple DNN algorithms may overload the agent. 

Love to hear more thoughts.

**Comment by miguelgfierro** [comment]
Adding more people for discussion

**Comment by anargyri** [comment]
I thought single node CPU for DNN training is not frequent. I guess we do not consider distributed training to multiple nodes, do we?  
We could also discuss the possible options on a call with @msalvaris.

**Comment by miguelgfierro** [comment]
At some point we could try to implement SAR on dask

**Comment by msalvaris** [comment]
I would vote for GPU only. Also we can use GPU or CPU with Dask. Do we have any idea how dl recommender algos perform with MKL-DNN?

**Comment by loomlike** [comment]
+1 to GPU only

**Comment by miguelgfierro** [comment]
We haven't done performance tests for the dl algos, they are still in development.

**Comment by danielsc** [comment]
When I look at a new github project, I would usually first install it on my Mac and try to run through some of the samples to get a feel for the quality of the repo and whether it seems to solve my problem.
If we constrain this repo to just GPU, we would lock out the users that don't have a standing DSVM or some other GPU available.
We would like to educate people on how to use the cloud to get more productive when doing recommenders, but we don't want to expect them to already be doing it. What better way to show the value of cloud compute, than showing how they can speed up their work by a factor of 5-10 when using a cloud machine rather than their laptop.  
So, I think we should make sure that users can use at least the quickstart notebooks of the repo with their laptop without a GPU.

**Comment by gramhagen** [comment]
I like the idea of being able to run through examples locally and having a clear path towards scaling solutions up. So far we haven't been as focused on supporting systems outside of Linux, which makes it challenging to replicate the examples. It's worth a separate discussion on how best to support that path.

I do think some of the deep learning approaches while feasible on CPU quickly become unreasonable to run at scale. If people want to play around with it locally without GPU I don't think we should make it impossible to do so, but just from a limited resources (human & computation) standpoint I think focusing on GPU only test environments for DL algos is a good starting point. 

If we focus the test cases on GPU, but have documentation that demonstrates how to run them without GPU would be sufficient for what you're interested in @danielsc ?

**Comment by miguelgfierro** [comment]
I think that's a fair ask. Now a question related to this that Daniel and I were discussing. 
If we support pytorch, TF, etc in CPU and GPU, would it be fair to do unit, smoke and integration tests only on GPU (to save computation time) and assume that the behaviour of CPU is the same as GPU but slower? Do people have a different experience?

**Comment by danielsc** [comment]
I just ran through the quick-start for NCF, FastAI and SAR, and here are the unexpected results:


Algo | GPU K80   Linux | CPU Core i7   Mac OS
-- | -- | --
NCF | Training model: neumf     Epoch 10 [4.36s]: train_loss = 0.257901      Epoch 20 [4.12s]: train_loss = 0.244856      Epoch 30 [4.20s]: train_loss = 0.239349      Epoch 40 [4.44s]: train_loss = 0.233747      Epoch 50 [4.03s]: train_loss = 0.230481  <br>Took **214.1773808002472** seconds for training.       <br>Took **9.189275979995728** seconds for prediction.       <br>MAP:        0.048241     NDCG:        0.198863     Precision@K:        0.179215     Recall@K:        0.099032 | Training model: neumf     Epoch 10 [3.63s]: train_loss = 0.268319      Epoch 20 [3.46s]: train_loss = 0.248716      Epoch 30 [3.59s]: train_loss = 0.239006      Epoch 40 [3.84s]: train_loss = 0.231270      Epoch 50 [3.70s]: train_loss = 0.227096      <br>Took **185.00423502922058** seconds for training.       <br>Took **12.697276830673218** seconds for prediction.       <br>MAP:        0.047037     NDCG:        0.193496     Precision@K:        0.175504     Recall@K:        0.100301
Fast AI | Total time: 00:21       epoch        train_loss        valid_loss   1        0.987165        0.983096   2        0.884710        0.890704   3        0.794637        0.853049   4        0.625724        0.838327   5        0.537200        0.838882       <br>Took **21.436105728149414** seconds for training.       <br>Took **1.989896535873413** seconds for 1433851   predictions.       <br>Model:        CollabLearner     Top K:        10     MAP:        0.021485     NDCG:        0.137494     Precision@K:        0.124284     Recall@K:        0.045587 | Total time: 00:15       epoch        train_loss        valid_loss   1        0.987165        0.983096   2        0.884710        0.890704   3        0.794637        0.853049   4        0.625724        0.838327   5        0.537200        0.838882       <br>Took **15.398819923400879** seconds for training.           <br>Took   **2.347848892211914** seconds for 1433851 predictions.       <br>Model:        CollabLearner     Top K:        10     MAP:        0.021485     NDCG:        0.137494     Precision@K:        0.124284     Recall@K:        0.045587
SAR | Took **0.5522489547729492** seconds for training.       <br>Took **0.12695932388305664** seconds for prediction.       <br>Model:        sar_ref     Top K:        10     MAP:        0.105815     NDCG:        0.373197     Precision@K:        0.326617     Recall@K:        0.175957 | Took   **0.5513231754302979** seconds for training.       <br>Took **0.0782170295715332** seconds for prediction.       <br>Model:        sar_ref     Top K:        10     MAP:        0.105815     NDCG:        0.373197     Precision@K:        0.326617     Recall@K:        0.175957

**Comment by danielsc** [comment]
I think we should make sure everything works fine on CPU when using our smallest dataset.
Here some numbers of some tests I ran today -- the takeways:
* for the algos we have today, CPU is working fine for small datasets, better than GPU..
* the fastai recommender does not benefit much from the GPU, only for larger dataset and only mildly. This makes sense, since the model is really shallow
* NCF doesn't seem to benefit from GPU at all -- quite the opposite (although the model is placed on the GPU, I checked) -- needs work

Algo | CPU Core i7   Mac OS conda_bare | GPU K80   Linux conda_bare | GPU K80    Linux conda_gpu | GPU P100   Linux conda_gpu
-- | -- | -- | -- | --
NCF   100k | Training model: neumf     <br>Epoch 10 [3.63s]:   train_loss = 0.268319      <br>Epoch 20 [3.46s]:   train_loss = 0.248716      <br>Epoch 30 [3.59s]:   train_loss = 0.239006      <br>Epoch 40 [3.84s]:   train_loss = 0.231270      <br>Epoch 50 [3.70s]:   train_loss = 0.227096      <br>   <br>Took 185.00423502922058 seconds for training.   <br>   <br>Took 12.697276830673218 seconds for   prediction.   <br>   <br>MAP:        0.047037     <br>NDCG:        0.193496     <br>Precision@K:        0.175504     <br>Recall@K:        0.100301 | Training model: neumf     <br>Epoch 10 [4.36s]:   train_loss = 0.257901      <br>Epoch 20 [4.12s]:   train_loss = 0.244856      <br>Epoch 30 [4.20s]:   train_loss = 0.239349      <br>Epoch 40 [4.44s]:   train_loss = 0.233747      <br>Epoch 50 [4.03s]:   train_loss = 0.230481      <br>   <br>Took 214.1773808002472 seconds for   training.   <br>   <br>Took 9.189275979995728 seconds for   prediction.   <br>   <br>MAP:        0.048241     NDCG:        0.198863     Precision@K:        0.179215     Recall@K:        0.099032 | Training model: neumf     <br>Epoch 10 [6.70s]:   train_loss = 0.269589      <br>Epoch 20 [6.74s]:   train_loss = 0.253282      <br>Epoch 30 [6.66s]:   train_loss = 0.245918      <br>Epoch 40 [6.59s]:   train_loss = 0.239419      <br>Epoch 50 [6.50s]:   train_loss = 0.236290      <br>   <br>Took 334.61992835998535 seconds for   training.   <br>   <br>Took 9.468753576278687 seconds for   prediction.     <br>   <br>MAP:        0.049774     <br>NDCG:        0.196829     <br>Precision@K:        0.175398     <br>Recall@K:        0.100898 | Training model: neumf     <br>Epoch 10 [6.01s]:   train_loss = 0.260690      <br>Epoch 20 [5.81s]:   train_loss = 0.250531      <br>Epoch 30 [5.95s]:   train_loss = 0.243845      <br>Epoch 40 [6.07s]:   train_loss = 0.237200      <br>Epoch 50 [5.83s]:   train_loss = 0.233626      <br>   <br>Took 299.45330786705017 seconds for   training.   <br>   <br>Took   8.658863067626953 seconds for prediction.   <br>   <br>MAP:        0.052095     <br>NDCG:        0.201553     <br>Precision@K:        0.183139     <br>Recall@K:        0.107493
NCF    1m | Training model: neumf     <br>Epoch 10 [51.29s]:   train_loss = 0.268177      <br>Epoch 20 [48.04s]:   train_loss = 0.260830      <br>Epoch 30 [47.90s]:   train_loss = 0.258196      <br>Epoch 40 [52.87s]:   train_loss = 0.256907      <br>Epoch 50 [52.03s]:   train_loss = 0.255662      <br>   <br>Took 2957.8880050182343 seconds for   training.   <br>   <br>Took 147.27565002441406 seconds for   prediction.   <br>   <br>MAP:        0.026098     <br>NDCG:        0.158897     <br>Precision@K:        0.147632     <br>Recall@K:        0.057360 |   | Training model: neumf     <br>Epoch 10 [82.97s]:   train_loss = 0.267686      <br>Epoch 20 [85.80s]:   train_loss = 0.259566       <br>Then the kernel somehow died | Training model: neumf     <br>Epoch 10 [73.06s]: train_loss = 0.265126      <br>Epoch 20 [73.47s]: train_loss = 0.258389    <br>Then the kernel somehow died
Fast AI   100k | <br>Total time: 00:15   <br>   <br>epoch        train_loss        valid_loss   <br>1        0.987165        0.983096   <br>2        0.884710        0.890704   <br>3        0.794637        0.853049   <br>4        0.625724        0.838327   <br>5        0.537200        0.838882   <br>   <br>Took 15.398819923400879   seconds for training.   <br>   <br>Took   2.347848892211914 seconds for 1433851 predictions.   <br>   <br>Model:        CollabLearner     <br>Top   K:        10     <br>MAP:        0.021485     <br>NDCG:        0.137494     <br>Precision@K:        0.124284     <br>Recall@K:        0.045587 |   | Total time: 00:21   <br>   <br>epoch        train_loss        valid_loss   <br>1        0.987165        0.983096   <br>2        0.884710        0.890704   <br>3        0.794637        0.853049   <br>4        0.625724        0.838327   <br>5        0.537200        0.838882   <br>   <br>Took 21.436105728149414   seconds for training.   <br>   <br>Took 1.989896535873413 seconds for   1433851 predictions.   <br>   <br>Model:        CollabLearner     <br>Top   K:        10     <br>MAP:        0.021485     <br>NDCG:        0.137494     <br>Precision@K:        0.124284     <br>Recall@K:        0.045587 | Total time: 00:19       <br>epoch        train_loss        valid_loss   <br>1        0.535954        0.863618   <br>2        0.603469        0.887373   <br>3        0.508026        0.887648   <br>4        0.366641        0.893734   <br>5        0.268254        0.895901   <br>   <br>Took   19.867988348007202 seconds for <br>training.   <br>   <br>Took   1.9045672416687012 seconds for 1433851 predictions.   <br>   <br>Model:        CollabLearner     <br>Top K:        10     <br>MAP:        0.021398     <br>NDCG:        0.135875     <br>Precision@K:        0.123542     <br>Recall@K:        0.047237
Fast AI    1m | Total time: 05:43   <br>epoch        train_loss        valid_loss   <br>1        0.925445        0.907547   <br>2        0.887913        0.891820   <br>3        0.849890        0.851792   <br>4        0.804398        0.800923   <br>5        0.762638        0.782159   <br>Took   344.67099022865295 seconds for training.   <br>   <br>Took   75.23807001113892 seconds for 21189590 predictions.   <br>   <br>Model:        CollabLearner     <br>Top   K:        10     <br>MAP:        0.023022     <br>NDCG:        0.168733     <br>Precision@K:        0.154827     <br>Recall@K:        0.050173 |   | Total time: 03:18   <br>   <br>epoch        train_loss        valid_loss   <br>1        0.925445        0.907547   <br>2        0.887913        0.891820   <br>3        0.849899        0.851789   <br>4        0.804382        0.800928   <br>5        0.762631        0.782160   <br>Took   199.38865399360657 seconds for training.   <br>   <br>Took   29.280792951583862 seconds for 21189590 predictions.   <br>   <br>Model:        CollabLearner     <br>Top   K:        10     <br>MAP:        0.023002     <br>NDCG:        0.168681     <br>Precision@K:        0.154728     <br>Recall@K:        0.050147 | Total time: 02:58   <br>epoch        train_loss        valid_loss   <br>1        0.925445        0.907547   <br>2        0.887913        0.891820   <br>3        0.849899        0.851789   <br>4        0.804382        0.800928   <br>5        0.762631        0.782160   <br>Took   179.35755825042725 seconds for training.   <br>   <br>Took   28.030783891677856 seconds for 21189590 predictions.   <br>   <br>Model:        CollabLearner     <br>Top K:        10     <br>MAP:        0.023002     <br>NDCG:        0.168681     <br>Precision@K:        0.154728     <br>Recall@K:        0.050147
SAR   100k | Took   0.5513231754302979 seconds for training.       <br>Took 0.0782170295715332 seconds for   prediction.       <br>Model:        sar_ref     <br>Top   K:        10     <br>MAP:        0.105815     <br>NDCG:        0.373197     <br>Precision@K:        0.326617     <br>Recall@K:        0.175957 |   | Took 0.5522489547729492 seconds for training.   <br>   <br>Took 0.12695932388305664 seconds   for prediction.   <br>   <br>Model:        sar_ref     <br>Top   K:        10     <br>MAP:        0.105815     <br>NDCG:        0.373197     <br>Precision@K:        0.326617     <br>Recall@K:        0.175957 |  
For reference:    Fast AI   Training   3 Epochs of Oxford-IIIT   Pet Dataset on   Resnet-50 | Too   long (probably hours) |   | Total time: 13:40 | Total time: 03:13

**Comment by miguelgfierro** [comment]
This is so good. Now we have some evidence supporting that the metrics supporting that the metrics are the same on CPU and GPU. Also, the time on CPU is faster with ML100k but slower with ML1M, which is expected.

@AaronHeee in relation to the kernel dying for NCF with ML100M, do you know what could be happening?

**Comment by miguelgfierro** [comment]
closing this, feel free to reopen if needed
