### ISSUE TITLE
[BUG] generate conda file is returning an error

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#488]
### *What* is affected by this bug?
generate conda file is returning an error

### In *which* platform does it happen?
* *Azure Data Science Virtual Machine.*

### *How* do we replicate the issue?
```
sh scripts/generate_conda_file.sh
scripts/generate_conda_file.sh: 64: scripts/generate_conda_file.sh: Syntax error: "(" unexpected (expecting "then")
```

**Comment by gramhagen** [comment]
it would be really great to refactor this to a python script that leverages the (conda api)[https://docs.conda.io/projects/conda/en/latest/api/python_api.html]
we could have a base set of dependencies in a list, and separate dependencies for each environment in different lists, then just run a single command to create the desired environment on any OS.

**Comment by jreynolds01** [comment]
Good catch. This is because `sh` isn't bash on ubuntu systems - it's `dash`. running as:

`bash scripts/generate_conda_file.sh`

or just running the script directly invokes bash instead.

`./scripts/generate_conda_file.sh`

Do you want me to change it to run on sh? I can adjust it if we want to run it using sh instead of bash.

**Comment by miguelgfierro** [comment]
I would suggest to have a quick fix now, so it can run on sh, to make sure that all the test pipelines work and that people following the documentation don't get problems. 

Afterwards we can implement Scott's suggestion.. I think this makes a lot of sense
