### ISSUE TITLE
Recommender base class

### ISSUE THREAD

**Issue by loomlike** [Microsoft/Recommenders#514]
### Description
As our recommenders algo suite is expanding, would be good to have a base class (or interface / abstract class whatever we want to call it) which defines a general recommender spec (e.g. fit, predict, recommend_k) and let reco algo classes extend (inherit) the base class so that all the algos have the same or at least similar interface.

This will lessen users' burden to move between algos.

We are already doing that but more explicit way may better.

### Expected behavior (i.e. solution)
```
class Recommender():
    def fit():
        raise not implemented error...

class SAR(Recommender):

class NCF(Recommender):

...
```

**Comment by gramhagen** [comment]
I like the idea of defining an interface that allows us to use common tools / execution patterns to train, predict / evaluate.

If people want to use it as a base class that might reduce additional coding if we have standard functions built in. Alternatively, we should be able to wrap algorithms and surface the same methods.

#464 @miguelgfierro is doing some related work for benchmarking, so that seems like a good starting point to define the necessary methods.

**Comment by miguelgfierro** [comment]
Closing this as it was discussed internally not to do base classes
