### ISSUE TITLE
run notebook on Azure Databricks get error

### ISSUE THREAD

**Issue by tengfei86** [Microsoft/Recommenders#529]
### Description
**als_movie_o16n.ipynb on databricks  I get error when execute codes below:**
`client = get_client_from_cli_profile(azure.mgmt.cosmosdb.CosmosDB,
                                    subscription_id=subscription_id)`

> Error Stack:
> CLIError                                  Traceback (most recent call last)
> <command-3006291621032396> in <module>()
> ----> 1 client = get_client_from_cli_profile(azure.mgmt.cosmosdb.CosmosDB)
>       2 
>       3 async_cosmosdb_create = client.database_accounts.create_or_update(
>       4     resource_group,
>       5     account_name,
> 
> /databricks/python/lib/python3.5/site-packages/azure/common/client_factory.py in get_client_from_cli_profile(client_class, **kwargs)
>      77         resource, _ = _client_resource(client_class, cloud)
>      78         credentials, subscription_id, tenant_id = get_azure_cli_credentials(resource=resource,
> ---> 79                                                                             with_tenant=True)
>      80         parameters.update({
>      81             'credentials': kwargs.get('credentials', credentials),
> 
> /databricks/python/lib/python3.5/site-packages/azure/common/credentials.py in get_azure_cli_credentials(resource, with_tenant)
>      46     """
>      47     profile = get_cli_profile()
> ---> 48     cred, subscription_id, tenant_id = profile.get_login_credentials(resource=resource)
>      49     if with_tenant:
>      50         return cred, subscription_id, tenant_id
> 
> /databricks/python/lib/python3.5/site-packages/azure/cli/core/_profile.py in get_login_credentials(self, resource, subscription_id, aux_subscriptions)
>     488 
>     489     def get_login_credentials(self, resource=None, subscription_id=None, aux_subscriptions=None):
> --> 490         account = self.get_subscription(subscription_id)
>     491         user_type = account[_USER_ENTITY][_USER_TYPE]
>     492         username_or_sp_id = account[_USER_ENTITY][_USER_NAME]
> 
> /databricks/python/lib/python3.5/site-packages/azure/cli/core/_profile.py in get_subscription(self, subscription)
>     450         subscriptions = self.load_cached_subscriptions()
>     451         if not subscriptions:
> --> 452             raise CLIError("Please run 'az login' to setup account.")
>     453 
>     454         result = [x for x in subscriptions if (
> 
> CLIError: Please run 'az login' to setup account.

### In which platform does it happen?

* Azure Databricks. 

### Other Comments
@jdhuntington @sverrejoh @bgianfo

**Comment by yueguoguo** [comment]
Looks like the error shows that you have not authenticate your workspace? See https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-cli if it helps.

**Comment by nikhilrj** [comment]
We're investigating this. For now you can manually log in on the head node of Databricks by adding a cell with the following code:

```
%sh
pip install azure-cli
az login
```

**Comment by jreynolds01** [comment]
This issue is caused by a new method of authentication within the azureml-sdk. As of version 1.0.10 of the sdk, it uses a different authentication method. So, the workspace.create() call authenticates for the azureml-sdk, but not the other azure modules. The `scripts/prepare_databricks_for_o16n.sh` script pins the version of the azureml-sdk to version 1.0.8 for this reason.

Solutions:
- Update the setup.md to use the pinned version of the azureml-sdk so that you don't have to log in twice.
- Update the notebook to install azure-cli on the head node.

Thoughts on which approach?

**Comment by roalexan** [comment]
FYI, I was hit by this today as well. Seems pretty important to resolve, since anyone will be blocked running this notebook. Another solution to consider (that worked for me): create an AAD registered app, grant it access to my newly created AML workspace, then instantiate a ServicePrincipalCredentials object in the notebook and use it to authenticate. I used the portal for much of this, probably could/should be converted to az CLI equivalents. My notebook code looks like: 

from azure.common.credentials import ServicePrincipalCredentials

credentials = ServicePrincipalCredentials(
  client_id = app_id,
  secret = app_key,
  tenant = tenant_id
)

client = get_client_from_cli_profile(azure.mgmt.cosmosdb.CosmosDB, credentials=credentials, subscription_id=subscription_id)

**Comment by tengfei86** [comment]
> We're investigating this. For now you can manually log in on the head node of Databricks by adding a cell with the following code:
> 
> ```
> %sh
> pip install azure-cli
> az login
> ```

Thanks

**Comment by tengfei86** [comment]
> This issue is caused by a new method of authentication within the azureml-sdk. As of version 1.0.10 of the sdk, it uses a different authentication method. So, the workspace.create() call authenticates for the azureml-sdk, but not the other azure modules. The `scripts/prepare_databricks_for_o16n.sh` script pins the version of the azureml-sdk to version 1.0.8 for this reason.
> 
> Solutions:
> 
> * Update the setup.md to use the pinned version of the azureml-sdk so that you don't have to log in twice.
> * Update the notebook to install azure-cli on the head node.
> 
> Thoughts on which approach?

Thanks , that  worked
