### ISSUE TITLE
[ASK] Retrieving latent factors from VW matrix factorization

### ISSUE THREAD

**Issue by szipkin** [Microsoft/Recommenders#750]
### Description

I'm using an Azure DSVM that has VW pre-installed and running the VW deep dive notebook. It shows 2 matrix factorization recommender methods and how to do training and scoring from them, but I would like to retrieve the latent factors or decomposed matrices from the methods for further processing in python. Or at least output the readable models or weights to a text file. 

I cannot find/run the gd_mf_weights file described from the VW example (https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Matrix-factorization-example) to produce the latent factors. How can I get the latent factors from the --rank and --lrq models?
 
### Other Comments
It is a great deep dive tutorial overall, but I just have this specific ask. Please advise. Thank you!

**Comment by gramhagen** [comment]
Right, currently on DSVMs only the VW binary exists. You can however use the invert_hash option to generate a more readable model.

example:
```vw --lrq ui7 -d train.dat -f vw.model --invert_hash vw.model.txt```

which will give you a file that contains the item, user, and global biases, as well as low rank weights for each item and user seen in train.dat

example, the weight vector for item 1058 is [-0.425035, 0.042227, 0.293272, 0.161824, -0.286626]
```
lrq^i^1058^1:104705:-0.425035
lrq^i^1058^2:104706:0.042227
lrq^i^1058^3:104707:0.293272
lrq^i^1058^4:104708:0.161824
lrq^i^1058^5:104709:-0.286626
```

doing the same for --rank models produces something a little harder to parse, you would need figure out what the columns are there.. =/

it is possible to clone the repo on DSVM and build vw + library files to use gd_mf_weights. Note you will need to retrain your model using the new vw binary otherwise the model files will not be compatible. (or you could checkout the 8.1.1 release version and build that)

**Comment by szipkin** [comment]
If I have the Ubuntu DSVM, does it already have the necessary tools to build vw + library files once I download the 8.1.1 release version there? (Meaning I can open up the terminal and run the build/install commands as described in VW wiki?) 

Thank you so much for your help!

**Comment by gramhagen** [comment]
yes, you can do that on an ubuntu dsvm

```
git clone https://github.com/VowpalWabbit/vowpal_wabbit.git
cd vowpal_wabbit
git checkout 3cf3f69279eab5a8f580c58b8eb5a3c87dd984df
make
library/gd_mf_weights --help
```

**Comment by gramhagen** [comment]
Let us know if you have further questions or issues, closing this for now.

**Comment by szipkin** [comment]
I trained a rank 40 model on the movielens data, but cannot retrieve the weights from the trained model with gd_mf_weights. I'm following the syntax from the matrix factorization example but it is giving me errors. Any advice?

Model training call:
`vw --rank 40 -q ui --l2 0.1 --learning_rate 0.015 --decay_learning_rate 0.97 --power_t 0 --passes 50 --cache_file movielens.cache -f movielens.reg -d train.vw`

Weights generating call:
`library/gd_mf_weights -I train.vw -O '/data/home/mlteam/notebooks/Recommenders-master/notebooks/Outputs/movielens' --vwparams '-q ui --rank 40 -i movielens.reg'`

Error:
```
WARNING: model file has set of {-q, --cubic, --interactions} settings stored, but they'll be OVERRIDEN by set of {-q, --cubic, --interactions} settings from command line.
creating quadratic features for pairs: ui

finished run
number of examples = 0
weighted example sum = 0
weighted label sum = 0
average loss = -nan
total feature number = 0
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injectorboost::program_options::multiple_occurrences >'
what(): option '--rank' cannot be specified more than once
Aborted (core dumped)
```

If I just run it without specifying rank and interaction variables, it doesn't return the same trained model, since the parameters displayed are different from before.
```
library/gd_mf_weights -I train.vw -O '/data/home/mlteam/notebooks/Recommenders-master/notebooks/Outputs/movielens' --vwparams '-i movielens.reg' 
creating quadratic features for pairs: ui 
Num weight bits = 18 
learning rate = 10 
initial_t = 1 
power_t = 0.5 
using no cache 
Reading datafile = 
num sources = 0 
Segmentation fault (core dumped)
```

If I run weights generation with the entire set of model training parameters, it just ignores my extra parameters (and finishes much faster than 50 passes would take) and returns same weights from a randomly initiated rank 40 model.
`library/gd_mf_weights -I train.vw -0 '/data/home/mlteam/notebooks/Recommenders-master/notebooks/Outputs/movielens' --vwparams '--rank 40 -q ui --l2 0.1 --learning_rate 0.015 --decay_learning_rate 0.97 --power_t 0 --passes 50 --cache_file movielens.cache -f movielens.reg -d train.vw'`

**Comment by gramhagen** [comment]
sorry to take so long on this.

you need to be careful with -i, -f when specifying the model when using gd_mf_weights. Also I believe the [existing example](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Matrix-factorization-example) on vw is no longer correct since the rank and interaction terms are stored in the model. Resulting in the errors you're seeing. My understanding is you should drop the --rank and -q params, but keep the rest (and make sure you reference the model using -i).

Example:
```
vw --rank 40 -q ui --l2 0.2 --learning_rate 0.015 --decay_learning_rate 0.97 --power_t 0 --passes 50 --cache_file movielens.cache -f movielens.reg -d train.vw
library/gd_mf_weights -I train.vw -O ./results --vwparams '--l2 0.1 --learning_rate 0.015 --decay_learning_rate 0.97 --power_t 0 --passes 50 --cache_file movielens.cache -i movielens.reg'
```

 If there are additional issue, it might be better to raise them with the vowpal wabbit repo: https://github.com/VowpalWabbit/vowpal_wabbit

**Comment by szipkin** [comment]
Thanks, Scott. I did post on VW github and found that the issues had to do with versioning and bugs. https://github.com/VowpalWabbit/vowpal_wabbit/issues/1851
https://github.com/VowpalWabbit/vowpal_wabbit/issues/1871
